name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$(date +%s)
    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository }}:$(date +%s)
