name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/schbenedikt/search-engine:latest # Ensure the correct tag is used to avoid multiple packages
          platforms: linux/amd64,linux/arm64

      - name: Extract image tag
        id: extract
        run: |
          DATE_TAG=$(date +'%Y%m%d')
          echo "image_tag=$DATE_TAG" >> $GITHUB_ENV

      - name: Build and push Docker image with date tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/schbenedikt/search-engine:${{ env.image_tag }}
          platforms: linux/amd64,linux/arm64
